env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  comma-dangle:
    - error
    - always-multiline
  no-console:
    - error
  brace-style:
    - error
    - stroustrup
